# Generated by Django 5.0.2 on 2025-06-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField(unique=True, verbose_name="token")),
                (
                    "blacklisted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="blacklisted at"
                    ),
                ),
            ],
            options={
                "verbose_name": "blacklisted token",
                "verbose_name_plural": "blacklisted tokens",
                "ordering": ["-blacklisted_at"],
            },
        ),
    ]
