# Generated by Django 5.0.2 on 2025-06-01 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("parking_lots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="date")),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="total revenue",
                    ),
                ),
                (
                    "total_reservations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total reservations"
                    ),
                ),
                (
                    "average_duration",
                    models.FloatField(default=0, verbose_name="average duration"),
                ),
                ("peak_hour", models.TimeField(null=True, verbose_name="peak hour")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "daily report",
                "verbose_name_plural": "daily reports",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ParkingLotReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="total revenue",
                    ),
                ),
                (
                    "total_reservations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total reservations"
                    ),
                ),
                (
                    "occupancy_rate",
                    models.FloatField(default=0, verbose_name="occupancy rate"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parking_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="parking_lots.parkinglot",
                    ),
                ),
            ],
            options={
                "verbose_name": "parking lot report",
                "verbose_name_plural": "parking lot reports",
                "ordering": ["-date", "parking_lot"],
                "unique_together": {("parking_lot", "date")},
            },
        ),
    ]
