# Generated by Django 5.2.1 on 2025-06-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyreport",
            name="occupancy_rate",
            field=models.FloatField(default=0, verbose_name="occupancy rate"),
        ),
        migrations.AddField(
            model_name="parkinglotreport",
            name="average_duration",
            field=models.FloatField(default=0, verbose_name="average duration"),
        ),
        migrations.AddField(
            model_name="parkinglotreport",
            name="peak_hour",
            field=models.TimeField(null=True, verbose_name="peak hour"),
        ),
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="year")),
                ("month", models.PositiveIntegerField(verbose_name="month")),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="total revenue",
                    ),
                ),
                (
                    "total_reservations",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total reservations"
                    ),
                ),
                (
                    "average_duration",
                    models.FloatField(default=0, verbose_name="average duration"),
                ),
                (
                    "average_occupancy_rate",
                    models.FloatField(default=0, verbose_name="average occupancy rate"),
                ),
                ("peak_day", models.DateField(null=True, verbose_name="peak day")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "monthly report",
                "verbose_name_plural": "monthly reports",
                "ordering": ["-year", "-month"],
                "unique_together": {("year", "month")},
            },
        ),
    ]
