# Generated by Django 5.0.2 on 2025-06-04 17:31

import app.api.reports.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_dailyreport_occupancy_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="average_duration",
            field=models.FloatField(
                default=0,
                validators=[app.api.reports.validators.validate_non_negative],
                verbose_name="average duration",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="date",
            field=models.DateField(
                unique=True,
                validators=[app.api.reports.validators.validate_future_date],
                verbose_name="date",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="occupancy_rate",
            field=models.FloatField(
                default=0,
                validators=[app.api.reports.validators.validate_percentage],
                verbose_name="occupancy rate",
            ),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="total_revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[app.api.reports.validators.validate_non_negative],
                verbose_name="total revenue",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="average_duration",
            field=models.FloatField(
                default=0,
                validators=[app.api.reports.validators.validate_non_negative],
                verbose_name="average duration",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="average_occupancy_rate",
            field=models.FloatField(
                default=0,
                validators=[app.api.reports.validators.validate_percentage],
                verbose_name="average occupancy rate",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="month",
            field=models.PositiveIntegerField(
                validators=[app.api.reports.validators.validate_month],
                verbose_name="month",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="total_revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                validators=[app.api.reports.validators.validate_non_negative],
                verbose_name="total revenue",
            ),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="year",
            field=models.PositiveIntegerField(
                validators=[app.api.reports.validators.validate_year],
                verbose_name="year",
            ),
        ),
        migrations.AlterField(
            model_name="parkinglotreport",
            name="average_duration",
            field=models.FloatField(
                default=0,
                validators=[app.api.reports.validators.validate_non_negative],
                verbose_name="average duration",
            ),
        ),
        migrations.AlterField(
            model_name="parkinglotreport",
            name="date",
            field=models.DateField(
                validators=[app.api.reports.validators.validate_future_date],
                verbose_name="date",
            ),
        ),
        migrations.AlterField(
            model_name="parkinglotreport",
            name="occupancy_rate",
            field=models.FloatField(
                default=0,
                validators=[app.api.reports.validators.validate_percentage],
                verbose_name="occupancy rate",
            ),
        ),
        migrations.AlterField(
            model_name="parkinglotreport",
            name="total_revenue",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[app.api.reports.validators.validate_non_negative],
                verbose_name="total revenue",
            ),
        ),
    ]
