version: '3.8'
name: $DOCKER_COMPOSE_TEST_NAME
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: zenxianie_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    command: >
      sh -c "pipenv run python manage.py migrate &&
             pipenv run python manage.py test app.test.accounts app.test.parking_lots app.test.reservations app.test.reports --verbosity=2"
    environment:
      - DJANGO_SECRET_KEY=test_secret_key
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DJANGO_CORS_ALLOWED_ORIGINS=http://localhost:5173
      - POSTGRES_DB=zenxianie_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ..:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy 