# Generated by Django 5.0.2 on 2025-06-03 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("new_reservation", "New Reservation"),
                            ("reservation_expired", "Reservation Expired"),
                            ("reservation_cancelled", "Reservation Cancelled"),
                            ("upcoming_reservation", "Upcoming Reservation"),
                            ("custom", "Custom Notification"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("unread", "Unread"), ("read", "Read")],
                        default="unread",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="notificatio_user_id_c760ba_idx"
                    ),
                    models.Index(fields=["type"], name="notificatio_type_94f703_idx"),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_fcd7aa_idx"
                    ),
                ],
            },
        ),
    ]
